name: uso consumo e-mail sender

on:
  workflow_dispatch:

permissions: write-all

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: process source table
        id: process
        env:
          GSA_CREDENTIALS: ${{ secrets.GSA_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          EMAIL_TO_FILIAL: ${{ secrets.EMAIL_MAP }}   # adjust name if needed
        shell: bash
        run: |
          set -e
          python scripts/data_calc.py | tee run.log
          grep '^UPDATED_SHEETS_JSON=' run.log >> "$GITHUB_OUTPUT"

      - name: Build last run status
        id: status
        shell: bash
        run: |
          set -e
          UPDATED='${{ steps.process.outputs.UPDATED_SHEETS_JSON }}'
          COUNT=$(python -c "import json; a=json.loads('''$UPDATED''' or '[]'); print(len(a))")
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
          cat > last_run_status.json <<EOF
          {"updated_sheets": $UPDATED, "count": $COUNT, "timestamp_utc": "$TS"}
          EOF
      
          echo "UPDATED_SHEETS_COUNT=$COUNT" >> "$GITHUB_OUTPUT"

       - name: Commit last run status
         shell: bash
         run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add last_run_status.json
            git commit -m "Update last run status" || echo "No changes"
            git push
      
      #- name: save sheets as pdf and send e-mail
        #env:
          #UPDATED_SHEETS_JSON: ${{ steps.process.outputs.UPDATED_SHEETS_JSON }}
          #GSA_CREDENTIALS: ${{ secrets.GSA_CREDENTIALS }}
          #SHEET_ID: ${{ secrets.SHEET_ID }}
          #EMAIL_TO: ${{ secrets.EMAIL_TO }}
          #GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
        #run: |
          #python scripts/send_email.py
